import ProjectModel
import SwiftParser
import Testing

@Suite struct GeneratedCodeTests {
    @Test(arguments: [
        "// swiftlint:disable all\n// Generated using SwiftGen — https://github.com/SwiftGen/SwiftGen\n",
        "// Generated by Sourcery 2.0 — DO NOT EDIT\n",
        "/* @generated by a code generator */\n",
    ])
    func `a generator's header marks the file generated`(header: String) {
        let tree = Parser.parse(source: header + "import Foundation\nenum Asset {}\n")

        #expect(GeneratedCode.isGenerated(path: "Sources/Sample/Assets.swift", tree: tree))
    }

    @Test(arguments: ["Sources/Sample/Generated/Strings.swift", "Sources/Sample/Model.generated.swift"])
    func `a generated path marks the file generated`(path: String) {
        #expect(GeneratedCode.isGenerated(path: path, header: ""))
    }

    @Test func `a hand-written file is not generated, even when a later comment names a generator`() {
        let tree = Parser.parse(
            source: """
                // Sample model.
                import Foundation

                // Generated using SwiftGen elsewhere; this file is hand-written.
                struct SampleModel {}
                """)

        #expect(!GeneratedCode.isGenerated(path: "Sources/Sample/SampleModel.swift", tree: tree))
        #expect(!GeneratedCode.isGenerated(path: "Sources/Sample/GeneratedReport.swift", header: ""))
    }
}
