public import SwiftSyntax

/// Recognizes files a generator wrote (SwiftGen, Sourcery, protobuf, ...).
/// Nobody edits them by hand, so a finding inside one is not actionable in
/// place, yet the code they contain still uses hand-written code.
public enum GeneratedCode {
    /// Header phrases generators write, matched case-insensitively.
    public static let headerMarkers: [String] = [
        "generated using",
        "generated by",
        "autogenerated",
        "auto-generated",
        "@generated",
        "do not edit",
    ]

    /// How much of the header is searched, in characters.
    public static let headerLength = 2048

    /// Whether the file at `path`, whose leading comments are `header`, is
    /// generated: a marker in the header, a `Generated` directory, or a
    /// `.generated.swift` name.
    /// - Complexity: O(1): at most ``headerLength`` characters are read.
    public static func isGenerated(path: String, header: some StringProtocol) -> Bool {
        if path.hasSuffix(".generated.swift") || path.split(separator: "/").contains("Generated") {
            return true
        }
        let head = header.prefix(headerLength).lowercased()
        return headerMarkers.contains { head.contains($0) }
    }

    /// Whether the parsed file at `path` is generated, reading only the
    /// comments before its first token.
    public static func isGenerated(path: String, tree: SourceFileSyntax) -> Bool {
        var header = ""
        let trivia = tree.firstToken(viewMode: .sourceAccurate)?.leadingTrivia ?? tree.endOfFileToken.leadingTrivia
        for piece in trivia {
            switch piece {
            case .lineComment(let text), .blockComment(let text), .docLineComment(let text),
                .docBlockComment(let text):
                header += text + "\n"
            default:
                break
            }
            if header.count >= headerLength { break }
        }
        return isGenerated(path: path, header: header)
    }
}
